KylinOLAP/Kylin

server/src/main/java/com/kylinolap/rest/filter/KylinCORSFilter.java, webapp/app/js/controllers/cubeEdit.js, webapp/app/js/controllers/cubes.js, webapp/app/partials/cubeDesigner/advanced_settings.html, webapp/app/partials/cubeDesigner/incremental.html, webapp/app/partials/jobs/job_submit.html
add cors filter &rm ng-init directive & add include,exclude info for date when build job.
=> add cors filter &rm ng-init directive & add include,exclude info for date when build job.

cube/src/test/java/com/kylinolap/cube/project/ProjectManagerTest.java, dictionary/src/test/java/com/kylinolap/dict/NumberDictionaryTest.java, invertedindex/src/main/java/com/kylinolap/invertedindex/model/IIDesc.java, job/src/test/java/com/kylinolap/job/hadoop/hive/JoinedFlatTableTest.java, metadata/src/main/java/com/kylinolap/metadata/MetadataManager.java, metadata/src/main/java/com/kylinolap/metadata/model/DataModelDesc.java, metadata/src/main/java/com/kylinolap/metadata/model/TableDesc.java, metadata/src/main/java/com/kylinolap/metadata/model/TblColRef.java, metadata/src/main/java/com/kylinolap/metadata/project/ProjectManager.java, metadata/src/test/java/com/kylinolap/metadata/model/TableDescTest.java, storage/src/test/java/com/kylinolap/storage/filter/BitMapFilterEvaluatorTest.java, storage/src/test/java/com/kylinolap/storage/filter/FilterSerializeTest.java, storage/src/test/java/com/kylinolap/storage/hbase/coprocessor/observer/AggregateRegionObserverTest.java
Make "databse" mandantory in TableDesc and updated some test cases
=> Inverted index

webapp/app/js/controllers/job.js, webapp/app/js/controllers/page.js, webapp/app/partials/query/query_detail.html
use safeApply in angularjs & set partial false when rerun
=> Ori staging

webapp/app/index.html, webapp/app/js/controllers/admin.js, webapp/app/js/controllers/cubeSchema.js, webapp/app/js/controllers/page.js, webapp/app/js/services/kylinProperties.js
=> timezone feature

webapp/app/js/controllers/cubeDimensions.js, webapp/app/js/controllers/cubeEdit.js, webapp/app/partials/cubeDesigner/dimensions.html, webapp/app/partials/cubeDesigner/incremental.html
=> rm deprecated code

webapp/app/partials/cubeDesigner/data_model.html
fix localytics/angular-chosen bug KYLIN-519
=> fix localytics/angular-chosen bug KYLIN-519

webapp/app/js/controllers/cubeEdit.js, webapp/app/js/controllers/cubeSchema.js, webapp/app/partials/cubeDesigner/incremental.html, webapp/app/partials/cubeDesigner/measures.html
=> fix ii cube save bug

webapp/app/js/controllers/cubes.js
=> fix build cube bug

webapp/app/js/controllers/cubeEdit.js, webapp/app/js/controllers/cubes.js, webapp/app/partials/cubeDesigner/advanced_settings.html, webapp/app/partials/cubeDesigner/incremental.html
filter partiton column use only date type column
=> filter partiton column use only date type column

job/src/test/java/org/apache/kylin/job/BuildCubeWithEngineTest.java, job/src/test/java/org/apache/kylin/job/BuildIIWithEngineTest.java
only delete related type job when run buildWithEngineTest
=> only delete related type job when run buildWithEngineTest

webapp/app/partials/cubes/cubes.html
stopPropagation for actions on cube
=> stopPropagation for actions on cube

webapp/app/js/controllers/cubeSchema.js, webapp/app/js/controllers/sourceMeta.js, webapp/app/js/model/projectModel.js, webapp/app/js/model/tableModel.js, webapp/app/partials/cubeDesigner/incremental.html, webapp/app/partials/cubes/cube_schema.html, webapp/app/partials/tables/source_table_tree.html
refactor loadHiveTable Code to tableModel & KYLIN-373
=> refactor loadHiveTable Code to tableModel & KYLIN-373

webapp/app/js/controllers/cubeEdit.js, webapp/app/partials/query/query.html, webapp/app/partials/query/query_detail.html
=> enhance query page

webapp/app/js/controllers/cubeEdit.js, webapp/app/js/controllers/cubeSchema.js, webapp/app/js/model/jobListModel.js, webapp/app/partials/cubeDesigner/advanced_settings.html
enhance aggregation group generate logic,add mandatory removed logic
=> enhance aggregation group generate logic,add mandatory removed logic

webapp/app/js/controllers/cubeEdit.js, webapp/app/partials/cubeDesigner/incremental.html
support 'string' and 'date' type column as options for partition column
=> support 'string' and 'date' type column as options for partition column

jdbc/src/main/java/org/apache/kylin/jdbc/util/SQLTypeMap.java
JDBC driver hat to distinguish between float and integer values.
=> [Kylin-626] Fix JDBC driver when returning float or double values

bin/kylin.sh
I was gettiing   out of memory  errors for   joins  with this configuration its working fine at lest for all quries I have tested on a sample cube build on 2 million data .
=> updated kylin.sh

webapp/app/js/controllers/cubeDimensions.js, webapp/app/js/controllers/cubeModel.js, webapp/app/less/component.less, webapp/app/partials/cubeDesigner/advanced_settings.html, webapp/app/partials/cubeDesigner/data_model.html, webapp/app/partials/cubeDesigner/dimensions.html, webapp/app/partials/cubes/cube_schema.html
fix UI issues when create&edit cube, KYLIN-220,KYLIN-516,KYLIN-517
=> fix UI issues when create&edit cube, KYLIN-220,KYLIN-516,KYLIN-517

webapp/app/js/controllers/cubeAdvanceSetting.js, webapp/app/js/filters/filter.js
, when bytes is 0 show '0 bytes' KYLIN-572
=> fix filter 0 bytes bug

server/src/main/resources/kylinSecurity.xml, webapp/app/js/controllers/auth.js, webapp/app/js/controllers/cube.js, webapp/app/js/listeners.js
config right authorize url Kylin-570
=> config right authorize url Kylin-570

job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java, server/src/main/resources/kylinSecurity.xml, webapp/app/js/controllers/auth.js, webapp/app/js/controllers/cube.js, webapp/app/js/controllers/cubeAdvanceSetting.js, webapp/app/js/controllers/cubeDimensions.js, webapp/app/js/controllers/cubeModel.js, webapp/app/js/filters/filter.js, webapp/app/js/listeners.js, webapp/app/less/component.less, webapp/app/partials/cubeDesigner/advanced_settings.html, webapp/app/partials/cubeDesigner/data_model.html, webapp/app/partials/cubeDesigner/dimensions.html, webapp/app/partials/cubes/cube_schema.html
=> merge staging

job/pom.xml, script/download-tomcat.sh
change "! -eq" syntax to "!=" since we compare string instead of a number
=> change "! -eq" syntax to "!=" since we compare string instead of a number

jdbc/src/main/java/org/apache/kylin/jdbc/Driver.java, server/src/main/java/org/apache/kylin/rest/controller/CubeDescController.java
REST API get cube desc NullPointerException when cube is not exists
=> REST API get cube desc NullPointerException when cube is not exists
